<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getCurrentUserNGroup</value>
  <value name="encodeutf8">true</value>
  <value name="body">dHJ5IHsgDQoJLyogU2VydmljZSBOYW1lOiBnZXRDdXJyZW50VXNlck5Hcm91cA0KCSAqIERlc2Ny
aXB0aW9uOg0KCSAqIGdldEN1cnJlbnRVc2VyTkdyb3VwIHNlcnZpY2UgaXMgdXNlZCB0byByZXRy
aWV2ZSB0aGUgY3VycmVudCB1c2VyIG5hbWUgDQoJICogYW5kIGdyb3VwcyB0aGUgdXNlciBiZWxv
bmdzIHRvLg0KCSAqLw0KCQ0KCUlEYXRhQ3Vyc29yIGlkYyA9IHBpcGVsaW5lLmdldEN1cnNvcigp
Ow0KCVVzZXIgdGhlVXNlciA9IEludm9rZVN0YXRlLmdldEN1cnJlbnRVc2VyKCk7DQoJU3RyaW5n
IGN1cnJlbnRVc2VyID0gdGhlVXNlci5nZXROYW1lKCk7DQoJU3RyaW5nIGN1cnJlbnRHcm91cHNb
XSA9IChTdHJpbmdbXSkgKHRoZVVzZXIubWVtYmVyc2hpcE5hbWVzKCkudG9BcnJheShuZXcgU3Ry
aW5nWzBdKSk7DQoJaWRjLmluc2VydEFmdGVyKCJjdXJyZW50VXNlciIsIGN1cnJlbnRVc2VyKTsN
CglpZGMuaW5zZXJ0QWZ0ZXIoImN1cnJlbnRHcm91cHMiLCBjdXJyZW50R3JvdXBzKTsNCglpZGMu
ZGVzdHJveSgpOw0KfSBjYXRjaCAoRXhjZXB0aW9uIGV4Yykgew0KCVNlcnZlckFQSS5sb2dFcnJv
cihleGMpOw0KCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKGV4Yy50b1N0cmluZygpKTsNCn0=
</value>
</Values>
